{% set name = "opentelemetry-instrumentation-elasticsearch" %}
{% set version = "0.26b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-elasticsearch-{{ version }}.tar.gz
  sha256: 6d2010b43c3cccc90defc17025085aac8beb637c53f5a96a36d47de85523101f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.26b1
    - opentelemetry-semantic-conventions ==0.26b1
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test ==0.24b0
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test ==0.25b0
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test ==0.25b2
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.26b1
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-elasticsearch
  summary: OpenTelemetry elasticsearch instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
