{% set name = "opentelemetry-instrumentation-elasticsearch" %}
{% set version = "0.33b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-elasticsearch-{{ version }}.tar.gz
  sha256: ec2975c6139c06455897e40db6d689937de6a10ab3baabff303bb03090e5bc8b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.33b0
    - opentelemetry-semantic-conventions ==0.33b0
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test ==0.24b0
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test ==0.25b0
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test ==0.25b2
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.26b1
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.27b0
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.28b0
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.28b1
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.29b0
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.30b0
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.30b1
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.31b0
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.32b0
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.33b0
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-elasticsearch
  summary: OpenTelemetry elasticsearch instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
